export const products = [
  {
    id: 1,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 2,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 3,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 4,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 5,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 6,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  },
  {
    id: 7,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 8,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 9,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 10,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 11,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 12,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  },
  {
    id: 13,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 14,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 15,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 16,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 17,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 18,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  },
  {
    id: 19,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 20,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 21,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 22,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 23,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 24,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  },
  {
    id: 25,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 26,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 27,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 28,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 29,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 30,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  },
  {
    id: 31,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 32,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 33,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 34,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 35,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 36,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  },
  {
    id: 37,
    title: "Cappuccino",
    link: "https://example.com/cappuccino",
    thumbnail: "/images/Cup.webp",
  },
  {
    id: 38,
    title: "Espresso Machine",
    link: "https://example.com/espresso-machine",
    thumbnail: "/images/blues.webp",
  },
  {
    id: 39,
    title: "Fresh Croissant",
    link: "https://example.com/fresh-croissant",
    thumbnail: "/images/coffees.webp",
  },
  {
    id: 40,
    title: "Latte Art",
    link: "https://example.com/latte-art",
    thumbnail: "/images/latteArt.webp",
  },
  {
    id: 41,
    title: "Coffee Beans",
    link: "https://example.com/cafe-interior",
    thumbnail: "/images/beans.webp",
  },
  {
    id: 42,
    title: "Iced Coffee",
    link: "https://example.com/iced-coffee",
    thumbnail: "/images/Iced.webp",
  }
];
